version: '3.7'

services:
  pg:
    image: bitnami/postgresql:13.17.0
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=fairy
    volumes:
      - ./docker:/docker-entrypoint-initdb.d